dbt_s3:  
  target: dev
  outputs:
    dev:
      type: postgres
      host: airflow-postgres-minio      
      user: airflow         
      password: airflow 
      port: 5432             
      dbname: airflow   
      schema: public         
      threads: 1           
